### ISSUE TITLE
[chaos-k8s] Add support for partition/isolation

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#1336]
This is an umbrella issue part of https://github.com/paritytech/zombienet/issues/1092

Check exploration on manifest of :
- https://github.com/https://github.com/paritytech/zombienet-sdk/issues/18
- https://github.com/https://github.com/paritytech/zombienet-sdk/issues/17

We want to add support in both Network config (spawn) and D.S.L (test-runner) to add/remove/modify partition/isolation of the network.

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/zombienet/issues/1337
- [ ] https://github.com/paritytech/zombienet/issues/1338
- [ ] https://github.com/paritytech/zombienet/issues/1339
- [ ] https://github.com/paritytech/zombienet/issues/1340
```
