### ISSUE TITLE
[infra] Improving observability / monitoring

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet#797]
(Internal infra issue)

Hi @emamihe, this is an umbrella issue with some  issues that we should address `asap` in order to maintain the performance for all the teams.

# Improving observability / monitoring

## Issue
At the moment we don't have a clear way to visualize the current state of our cluster, we should have a simple way to map `namespaces` with `pipeline's jobs` and make more easy to detect leaking jobs.

### Task
- [x] Add `annotations` in each namespace created by our CI.
- [x] Add a cronjob that monitoring `ns` that are up for more than `x` amount of time and notify us to review. (we can also -crosscheck with the CI)
- [ ] Finish `auth` system integration.

## Issue 
We should have some kind of monitoring in place to detect spike in usage, like we had last week were nodes were reaching the scaling limit.

### Task
- [x] I think this could be easy be done why some of the services provided by our cloud provider.

## Issue
There are random failures in namespaces, we need to track them and review the cause since sometimes is just an scheduler issue. Also, we could find a way to *retry* between the same job when we detect and internal fail.

## Tasks

- [x] #800 

## Issue
Allow to trigger jobs manually and not, this will allow users to not run big networks in each pr (push).

## Task
- [x] Investigate how to generate the jobs in gitlab but don't auto-trigger and allow users to manually trigger.

Thanks!!

---
Update

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/zombienet/issues/1027
- [ ] https://github.com/paritytech/zombienet/issues/1028
- [ ] https://github.com/paritytech/zombienet/issues/1029
```

**Comment by pepoviola** [comment]
Hi @emamihe, as we talk the auth system will be implemented in the new version. Closing here now and we re-visit the task next quarter.
Thanks!
